spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ecommerce-channel
    password: ecommerce-channel
    virtual-host: ecommerce-checkout
  data:
    redis:
      host: localhost
      port: 6379
      password:
    mongodb:
      database: ecommerce_db
      uri: mongodb://admin:secret@localhost:27017/ecommerce_db?authSource=admin
      repositories:
        enabled: true

server:
  port: 8383

management:
  server:
    port: 9393

feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000
        loggerLevel: FULL # NONE, BASIC, HEADERS, FULL

client:
  via-cep:
    url: https://viacep.com.br/
  ecommerce-checkout:
    url: http://localhost:8181/