logging:
  level:
    br.com.alc.ecommerce.channel.infrastructure: DEBUG
    org.springframework:
      ampq: TRACE
      boot.context: INFO
      ws.client: TRACE
      ws.soap: TRACE
      web: WARN

spring:
  application:
    name: api-ecommerce-channel
  messages:
    basename: i18n/messages
  jmx:
    default-domain: ~project.artifactId~
  main:
    allow-bean-definition-overriding: true
  cache:
    redis:
      time-to-live: 172800
    type: redis
  rabbitmq:
    host: localhost
    port: 5672
    username: null
    password: null
    virtual-host: ecommerce-checkout
    listener:
      simple:
        auto-startup: true
    order-bot-exchange: order-bot-exchange
    order-generator-queue: order-generator-queue
    order-exchange: order-exchange
    order-queue: order-queue
    sale-callback-queue: sale-callback-queue
  web:
    locale: pt_BR
    locale-resolver: accept_header
  data:
    redis:
      repositories:
        enabled: false
      host: localhost
      port: 6379
      password: null
    mongodb:
      database:
      authentication-database:
      uri: mongodb://localhost:27017/ecommerce_db
      repositories:
        enabled: true
  mail:
    host: null
    port: 25
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          connectiontimeout: 30000
          timeout: 30000
          writetimeout: 30000

server:
  compression:
    enabled: true
  port: 8181
  servlet:
    context-path: /

endpoints:
  prometheus:
    id: metrics
    enabled: true
    sensitive: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

feign:
  circuitbreaker:
    enable: true
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000
        loggerLevel: BASIC # NONE, BASIC, HEADERS, FULL

resilience4j:
  circuitbreaker:
    instances:
      order-invoicer-circuitbreaker:
        slidingWindowType: TIME_BASED
        slidingWindowSize: 60
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 20s

management:
  server:
    port: 9191
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: /metrics
      exposure:
        include: '*'
        exclude: metrics
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  health:
    redis:
      enabled: false

client:
  via-cep:
    url: http://localhost:9093/api-via-cep/
  ecommerce-checkout:
    url: http://localhost:9094/api-ecommerce-checkout/